<?php

// Template list
return [
    // Gamer control panel page template
    // Generated by webapp
    'gamercp_page',
    // Cadre control panel page template
    // Generated by webapp
    'cadrecp_page',
    // Community memberlist page template
    // Generated by webapp
    'memberlist_page',
    // Community stats page template
    // Generated by webapp
    'stats_page',
    // Recruitment form page template
    // Generated by webapp
    'recruitment_form_page',
    // User profile page template
    // Generated by webapp
    'member_profile_page',
    // Recruitment forum application button template
    'forumdisplay_newrecruitmentapplication',
    // Postbit badge template
    'postbit_badge'
];
